### ISSUE TITLE
Kata seperti 'sabar' dan 'tersaji' tidak ada.

### ISSUE THREAD

**Issue by regabut** [damzaky/kumpulan-kata-bahasa-indonesia-KBBI#4]
kata yang ada saat ini mencapai 13rb kata, sementara menurut (https://oldi.lipi.go.id/public/Kamus%20Indonesia.pdf) ada sekitar 60rb kata dasar. Di dalam repo, kata 'sabar' dan 'tersaji' tidak ada. Apakah repo daftar kata akan dimutakhirkan kembali?

**Comment by damzaky** [comment]
updated di 165112a30f65507388866e88565b3fc115943add
