### ISSUE TITLE
Mismatched encoding in list_1.0.0.0.txt

### ISSUE THREAD

**Issue by aryakdaniswara** [damzaky/kumpulan-kata-bahasa-indonesia-KBBI#9]
In list_1.0.0.txt, a lot of the word that contains emphasis on a character (mainly found in Islamic terms) have mismatched encoding and replaced with `?`

For example in line 31, `abad al-ab?d` is should be `abad al-abīd`. Line 561 `ad-daulah al-isl?miyyah` should be  `ad-Daulah al-Islāmiyyah`  and so on. It mostly occurs in Islamic terms and does not occurs in list_0.5.1.txt

**Comment by aryakdaniswara** [comment]
cant find in the decompiler file: line 112057: xin nian kuai le (?????

file after decompiler: assets/dictdata/acu_nilai.txt

**Comment by damzaky** [comment]
Hi, thanks for the issue report, will look into it when I got the time for it. In the meantime, you can create a pull request for the fix, thanks
